apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration
spec:
  template:
    spec:
      containers:
      - name: kong-migration
        image: kong:latest
        # command: ["kong",  "migrations", "bootstrap", "-v"]
        user: root
        command: ["/bin/sh","-c"]
        args: ["apk add --no-cache curl git gcc musl-dev 
                && luarocks install luaossl OPENSSL_DIR=/usr/local/kong CRYPTO_DIR=/usr/local/kong 
                && kong  migrations bootstrap -v"]
        env:
        - name: KONG_PG_HOST
          valueFrom:
            configMapKeyRef:
              name: kong-migration-config
              key: KONG_PG_HOST
        - name: KONG_PG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: kong-migration-config
              key: KONG_PG_DATABASE
        - name: KONG_PG_USER
          valueFrom:
            configMapKeyRef:
              name: kong-migration-config
              key: KONG_PG_USER
        - name: KONG_PG_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: kong-migration-config
              key: KONG_PG_PASSWORD
      restartPolicy: Never
      