apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration
spec:
  template:
    spec:
      containers:
      - name: kong-migration
        image: kong:2.8.0-alpine
        # command: ["kong",  "migrations", "bootstrap", "-v"]
        command: ["/bin/sh","-c"]
        args: ["kong migrations bootstrap"]
        env:
        - name: KONG_PG_HOST
          valueFrom:
            configMapKeyRef:
              name: kong-migration-config
              key: KONG_PG_HOST
        - name: KONG_PG_DATABASE
          valueFrom:
            configMapKeyRef:
              name: kong-migration-config
              key: KONG_PG_DATABASE
        - name: KONG_PG_USER
          valueFrom:
            configMapKeyRef:
              name: kong-migration-config
              key: KONG_PG_USER
        - name: KONG_PG_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: kong-migration-config
              key: KONG_PG_PASSWORD
      restartPolicy: Never
      