apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-dev
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: tcp-mysql
      nodePort: 33060
  selector:
    app: mysql
  sessionAffinity: None
  type: NodePort