apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana-dev
spec:
  ports:
    - port: 4000
      protocol: TCP
      targetPort: http-grafana
      nodePort: 32000
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort