apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-pg-admin-pvc
  namespace: kong-data
spec:
  # storageClassName: localdisk
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi