apiVersion: v1
kind: Service
metadata:
  name: kong-pg-admin-svc
  namespace: kong-data
spec:
  type: ClusterIP
  selector:
    app: kong-pg-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# DNS kong-pg-admin-svc.kong-data.svc.cluster.local