apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-pg-database
  namespace: argocd
spec:
  destination:
    namespace: kong
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./k8s/development/platform/api-gateway/kong/application/
    repoURL: https://github.com/PanupongDeve/application-platform
    targetRevision: HEAD
