kind: PersistentVolume
apiVersion: v1
metadata:
  name: pg-admin-pv
  namespace: {{ .Values.project }}-{{ .Values.environment }}
spec:
  storageClassName: localdisk
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/pg_data/output
