apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-admin-pvc
  namespace: {{ .Values.project }}-{{ .Values.environment }}
spec:
  # storageClassName: localdisk
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi