apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-admin-config
  namespace: {{ .Values.project }}-{{ .Values.environment }}
  labels:
    app: pgdata
data:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.config.email }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.config.password }}
  PGADMIN_CONFIG_SERVER_MODE: 'False'


  # PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  # PGADMIN_DEFAULT_PASSWORD: admin
  # PGADMIN_CONFIG_SERVER_MODE: 'False'
