apiVersion: v1
kind: Service
metadata:
  name: pg-admin-svc
  namespace: {{ .Values.project }}-{{ .Values.environment }}
spec:
  type: {{ .Values.networking.type }}
  selector:
    app: pg-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-pg-admin
      nodePort: {{ .Values.networking.nodePort }}


# DNS kong-pg-admin-svc.<namespace>.svc.cluster.local