apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pg-admin-localdisk
  namespace: pg-admin
provisioner: kubernetes.io/no-provisioner
# provisioner: microk8s.io/hostpath
allowVolumeExpansion: true