apiVersion: v1
kind: Service
metadata:
  name: pg-admin-svc
  namespace: pg-admin
spec:
  type: NodePort
  selector:
    app: pg-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-pg-admin
      nodePort: 32080


# DNS kong-pg-admin-svc.<namespace>.svc.cluster.local