# helm template mysql-helm/ > mysql-helm-output/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: demo-dev
    server: https://kubernetes.default.svc
  project: demo
  source:
    path: k8s/development/platform/database/mysql/mysql-helm-output/
    repoURL: https://github.com/PanupongDeve/application-platform
    targetRevision: HEAD