apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: {{ .Values.project }}-{{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: bitnami/mysql:{{ .Values.mysql.version }}
          ports:
          - containerPort: 3306
            name: tcp-mysql
            protocol: TCP
          volumeMounts:
            - mountPath: /bitnami/mysql/data
              name: mysql-pv
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: MYSQL_PASSWORD

      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
      