apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: localdisk
  namespace: kong-data
provisioner: kubernetes.io/no-provisioner
# provisioner: microk8s.io/hostpath
allowVolumeExpansion: true