kind: PersistentVolume
apiVersion: v1
metadata:
  name: kong-pv
  namespace: kong-data
spec:
  storageClassName: localdisk
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/pg_data/output
